"""
Django settings for keep_up project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from celery.schedules import crontab
from dotenv import load_dotenv
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Load environment variables from .env file
env_path = Path(__file__).resolve().parent.parent / ".env"
load_dotenv(dotenv_path=env_path)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-ow2%2i0&!qz#+#22(6m5u!_vrijev@3_x@(9yj$*tvl@fku$n*"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # Package apps
    "safedelete",
    # Custom added apps
    "users.apps.UsersConfig",
    "event_bus",
    "todos.apps.TodosConfig",
    "agenda.apps.AgendaConfig",
    # Documentation
    "drf_spectacular",
]

LOGGING = {
    "version": 1,
    "disable_existing_loggers": True,
    "formatters": {
        "standard": {"format": "%(asctime)s [%(levelname)s]- %(message)s"},
        "json": {
            "()": "keep_up.log_formatter.StandardJSONLogFormatter",
        },
    },
    "handlers": {
        "console": {
            "level": "INFO",
            "class": "logging.StreamHandler",
            "formatter": "json",
        },
    },
    "loggers": {
        "django": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": True,
        },
        "django.request": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
        "django.server": {
            "handlers": [],
            "level": "INFO",
            "propagate": False,
        },
        "keep_up": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
    },
}

# Verisafe setup
# No default base url: each environment supplies its own, so a missing value
# fails loudly instead of silently pointing a QA deployment at production.
VERISAFE_BASE_URL = os.getenv("VERISAFE_BASE_URL")
VERISAFE_API_KEY = os.getenv("VERISAFE_API_KEY")
VERISAFE_TIMEOUT = float(os.getenv("VERISAFE_TIMEOUT", "10"))
VERISAFE_RETRIES = int(os.getenv("VERISAFE_RETRIES", "2"))


# Rabbit mq setup
RABBITMQ_USER = os.getenv("RABBITMQ_USER", None)
RABBITMQ_PASSWORD = os.getenv("RABBITMQ_PASSWORD", None)
RABBITMQ_HOST = os.getenv("RABBITMQ_HOST", None)
RABBITMQ_PORT = os.getenv("RABBITMQ_PORT", None)
RABBITMQ_VHOST = os.getenv("RABBITMQ_VHOST", None)


# Celery setup
CELERY_BROKER_URL = f"amqp://{RABBITMQ_USER}:{RABBITMQ_PASSWORD}@{RABBITMQ_HOST}:{RABBITMQ_PORT}/{RABBITMQ_VHOST}"
CELERY_TIMEZONE = "UTC"
CELERY_RESULT_BACKEND = "rpc://"

# UUIDs are not JSON serialisable, so every task signature takes str(uuid).
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_ACCEPT_CONTENT = ["json"]

# Acknowledge after the task finishes, so a worker dying mid-sync redelivers
# the job instead of dropping it. Sync tasks are written to be idempotent.
CELERY_TASK_ACKS_LATE = True
CELERY_WORKER_PREFETCH_MULTIPLIER = 1

CELERY_TASK_DEFAULT_QUEUE = "keep_up"
CELERY_TASK_ROUTES = {"todos.tasks.*": {"queue": "google_sync"}}

CELERY_BEAT_SCHEDULE = {
    # Catches records whose enqueue was lost to a worker restart, and retries
    # anything that previously failed.
    "sweep-stale-syncs": {
        "task": "todos.tasks.sweep_stale_syncs",
        "schedule": crontab(minute="*/15"),
    },
    # Backfill: a user who links Google later gets their existing records
    # pushed without having to touch anything.
    "backfill-skipped-syncs": {
        "task": "todos.tasks.sweep_stale_syncs",
        "schedule": crontab(hour=3, minute=0),
        "kwargs": {"include_skipped": True},
    },
}

# Google Tasks sync tuning
GOOGLE_SYNC_STALE_AFTER_MINUTES = int(
    os.getenv("GOOGLE_SYNC_STALE_AFTER_MINUTES", "15")
)
GOOGLE_SYNC_SWEEP_BATCH_SIZE = int(os.getenv("GOOGLE_SYNC_SWEEP_BATCH_SIZE", "500"))


REST_FRAMEWORK = {
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_PERMISSION_CLASSES": [],
    "DEFAULT_AUTHENTICATION_CLASSES": [],
    "DEFAULT_PAGINATION_CLASS": "keep_up.pagination.StandardResultsSetPagination",
    "PAGE_SIZE": 100,
}

SPECTACULAR_SETTINGS = {
    "TITLE": "Keep Up API",
    "DESCRIPTION": "Task management API documentation for the Academia Platform.",
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
}

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "keep_up.middlewares.request_logging_middleware.RequestLoggingMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "keep_up.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "keep_up.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql_psycopg2",
        "NAME": os.getenv("DB_NAME"),
        "USER": os.getenv("DB_USER"),
        "PASSWORD": os.getenv("DB_PASS"),
        "HOST": os.getenv("DB_HOST"),
        "PORT": os.getenv("DB_PORT"),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
