# Generated by Django 6.0.2 on 2026-03-14 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_avatar_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="avatar_url",
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
