# Generated by Django 6.0.4 on 2026-05-17 17:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_user_avatar_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="OauthToken",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("google", "google"),
                            ("apple", "apple"),
                            ("github", "gitHub"),
                        ],
                        max_length=60,
                    ),
                ),
                ("external_user_id", models.CharField(max_length=255)),
                ("access_token", models.TextField(blank=True, null=True)),
                ("access_token_secret", models.TextField(blank=True, null=True)),
                ("refresh_token", models.TextField(blank=True, null=True)),
                ("scopes", models.JSONField(blank=True, default=list)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="oauth_tokens",
                        to="users.user",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user", "provider"],
                        name="users_oauth_user_id_ef65ca_idx",
                    ),
                    models.Index(
                        fields=["expires_at"], name="users_oauth_expires_50dc56_idx"
                    ),
                ],
                "unique_together": {("user", "provider")},
            },
        ),
    ]
