# Generated by Django 6.0.4 on 2026-07-27 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_oauthtoken"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="oauthtoken",
            unique_together=None,
        ),
        migrations.RemoveIndex(
            model_name="oauthtoken",
            name="users_oauth_user_id_ef65ca_idx",
        ),
        migrations.RemoveIndex(
            model_name="oauthtoken",
            name="users_oauth_expires_50dc56_idx",
        ),
        migrations.DeleteModel(
            name="OauthToken",
        ),
    ]
