# Generated by Django 5.2.4 on 2025-08-17 12:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "deleted",
                    models.DateTimeField(db_index=True, editable=False, null=True),
                ),
                (
                    "deleted_by_cascade",
                    models.BooleanField(default=False, editable=False),
                ),
                (
                    "id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("summary", models.CharField(max_length=1024)),
                ("description", models.TextField(blank=True, null=True)),
                ("location", models.CharField(blank=True, max_length=1024, null=True)),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
                ("all_day", models.BooleanField(default=False)),
                ("timezone", models.CharField(default="UTC", max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("confirmed", "Confirmed"),
                            ("tentative", "Tentative"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="confirmed",
                        max_length=32,
                    ),
                ),
                (
                    "transparency",
                    models.CharField(
                        choices=[
                            ("opaque", "Opaque (blocks time on calendar)"),
                            ("transparent", "Transparent (doesn't block time)"),
                        ],
                        default="opaque",
                        max_length=32,
                    ),
                ),
                ("calendar_id", models.CharField(default="primary", max_length=255)),
                ("html_link", models.URLField()),
                ("created", models.DateTimeField()),
                ("updated", models.DateTimeField()),
                ("etag", models.CharField(max_length=255)),
                ("attendees", models.JSONField(blank=True, default=list)),
                ("reminders", models.JSONField(blank=True, default=dict)),
                ("recurrence", models.JSONField(blank=True, default=list)),
                ("owner_id", models.UUIDField(default=uuid.uuid4)),
            ],
            options={
                "ordering": ["start_time"],
            },
        ),
    ]
