# Generated by Django 5.2.4 on 2025-08-17 14:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['start_time'], 'verbose_name': 'Calendar Event', 'verbose_name_plural': 'Calendar Events'},
        ),
        migrations.AlterField(
            model_name='event',
            name='all_day',
            field=models.BooleanField(default=False, help_text='Whether this is an all-day event'),
        ),
        migrations.AlterField(
            model_name='event',
            name='attendees',
            field=models.JSONField(blank=True, default=list, help_text='List of event attendees'),
        ),
        migrations.AlterField(
            model_name='event',
            name='calendar_id',
            field=models.CharField(default='primary', help_text='Google Calendar ID', max_length=255),
        ),
        migrations.AlterField(
            model_name='event',
            name='created',
            field=models.DateTimeField(help_text='When event was created in Google Calendar'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, help_text='Detailed event description', null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=models.DateTimeField(help_text='Event end date and time'),
        ),
        migrations.AlterField(
            model_name='event',
            name='etag',
            field=models.CharField(help_text='ETag for concurrency control', max_length=255),
        ),
        migrations.AlterField(
            model_name='event',
            name='html_link',
            field=models.URLField(help_text='URL to view event in Google Calendar'),
        ),
        migrations.AlterField(
            model_name='event',
            name='id',
            field=models.CharField(help_text='Google Calendar Event ID', max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(blank=True, help_text='Event location', max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='owner_id',
            field=models.UUIDField(default=uuid.uuid4, help_text='User who owns this event'),
        ),
        migrations.AlterField(
            model_name='event',
            name='recurrence',
            field=models.JSONField(blank=True, default=list, help_text='Recurrence rules for repeating events'),
        ),
        migrations.AlterField(
            model_name='event',
            name='reminders',
            field=models.JSONField(blank=True, default=dict, help_text='Event reminder settings'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.DateTimeField(help_text='Event start date and time'),
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('confirmed', 'Confirmed'), ('tentative', 'Tentative'), ('cancelled', 'Cancelled')], default='confirmed', help_text='Event status', max_length=32),
        ),
        migrations.AlterField(
            model_name='event',
            name='summary',
            field=models.CharField(help_text='Event title or summary', max_length=1024),
        ),
        migrations.AlterField(
            model_name='event',
            name='timezone',
            field=models.CharField(default='UTC', help_text='Event timezone', max_length=64),
        ),
        migrations.AlterField(
            model_name='event',
            name='transparency',
            field=models.CharField(choices=[('opaque', 'Opaque (blocks time on calendar)'), ('transparent', "Transparent (doesn't block time)")], default='opaque', help_text='Whether event blocks time on calendar', max_length=32),
        ),
        migrations.AlterField(
            model_name='event',
            name='updated',
            field=models.DateTimeField(help_text='When event was last updated in Google Calendar'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['owner_id', 'start_time'], name='agenda_even_owner_i_3d9693_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['start_time', 'end_time'], name='agenda_even_start_t_b5e438_idx'),
        ),
    ]
