# Generated by Django 6.0.4 on 2026-09-30 07:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agenda", "0002_alter_event_options_alter_event_all_day_and_more"),
        ("todos", "0017_google_pull_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="task",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="agenda_event",
                to="todos.task",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="calendar_id",
            field=models.CharField(
                default="primary", help_text="Legacy Google Calendar ID", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="created",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="etag",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Legacy Google Calendar ETag",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="html_link",
            field=models.URLField(
                blank=True,
                default="",
                help_text="Legacy URL to view event in Google Calendar",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="id",
            field=models.CharField(
                default=uuid.uuid4,
                help_text="Local agenda event ID",
                max_length=255,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="owner_id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, help_text="User who owns this event"
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
