# Generated by Django 5.2.4 on 2025-07-29 11:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="owner_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
