# Generated by Django 5.2.4 on 2025-07-29 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todos", "0002_task_owner_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="kind",
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name="task",
            name="parent",
            field=models.CharField(blank=True, null=True),
        ),
    ]
