# Generated by Django 5.2.4 on 2025-07-29 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todos", "0004_alter_task_kind"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="completed",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
