# Generated by Django 5.2.4 on 2025-07-29 20:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todos", "0005_alter_task_completed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="owner_id",
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
