# Generated by Django 5.2.4 on 2025-07-30 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todos", "0006_alter_task_owner_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="due",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="task",
            name="notes",
            field=models.CharField(blank=True, max_length=8192, null=True),
        ),
        migrations.AlterField(
            model_name="task",
            name="updated",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
