# Generated by Django 5.2.4 on 2025-10-26 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("todos", "0007_alter_task_due_alter_task_notes_alter_task_updated"),
    ]

    operations = [
        migrations.RenameField(
            model_name="task",
            old_name="id",
            new_name="external_id",
        ),
    ]
