# Generated by Django 5.2.4 on 2025-10-26 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("todos", "0008_rename_id_task_external_id"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AssignmentInfo",
        ),
    ]
