# Generated by Django 5.2.4 on 2025-10-26 14:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todos", "0009_delete_assignmentinfo"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="id",
            field=models.UUIDField(default=uuid.uuid4, null=True),
        ),
    ]
