# Generated by Django 5.2.4 on 2025-10-26 14:21

import uuid
from django.db import migrations


def gen_uuid(apps, schema_editor):
    Task = apps.get_model("todos", "Task")
    for row in Task.objects.all():
        row.id = uuid.uuid4()
        print(f"Setting row id to {row.id} for external_id {row.external_id}")
        row.save(update_fields=["id"])


class Migration(migrations.Migration):

    dependencies = [
        ("todos", "0010_task_id"),
    ]

    operations = [
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]
