# Generated by Django 6.0.2 on 2026-04-24 16:17

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todos", "0013_alter_task_external_id_alter_task_id"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={"ordering": ["status", "due", "position"]},
        ),
        migrations.RemoveField(
            model_name="task",
            name="kind",
        ),
        migrations.RemoveField(
            model_name="task",
            name="self_link",
        ),
        migrations.RemoveField(
            model_name="task",
            name="updated",
        ),
        migrations.RemoveField(
            model_name="task",
            name="web_view_link",
        ),
        migrations.AddField(
            model_name="task",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="task",
            name="last_synced_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="priority",
            field=models.CharField(
                choices=[
                    ("none", "None"),
                    ("low", "Low"),
                    ("medium", "Medium"),
                    ("high", "High"),
                ],
                default="none",
                help_text="Local priority. Not synced to Google Tasks.",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="sync_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("synced", "Synced"),
                    ("failed", "Failed"),
                ],
                db_index=True,
                default="pending",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="task",
            name="completed",
            field=models.DateTimeField(
                blank=True,
                help_text="Set automatically when status changes to completed.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="deleted",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="task",
            name="due",
            field=models.DateField(
                blank=True,
                help_text="Google Tasks only stores the date, not the time.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="etag",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Google Tasks ETag for conflict detection on updates.",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="external_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Google Tasks task ID. Empty until first sync.",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="hidden",
            field=models.BooleanField(
                default=False,
                help_text="Set by Google when a completed task's list is cleared. Read-only after sync.",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="owner_id",
            field=models.UUIDField(db_index=True),
        ),
        migrations.AlterField(
            model_name="task",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                help_text="Parent task for subtasks. One level deep only (Google Tasks constraint).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="subtasks",
                to="todos.task",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="position",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Ordering string from Google Tasks. Used to preserve sort order after sync.",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[("needsAction", "Needs Action"), ("completed", "Completed")],
                default="needsAction",
                max_length=32,
            ),
        ),
        migrations.CreateModel(
            name="Attachment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("owner_id", models.UUIDField(db_index=True)),
                (
                    "source",
                    models.CharField(
                        choices=[("local", "Local"), ("google", "Google")],
                        db_index=True,
                        default="local",
                        max_length=16,
                    ),
                ),
                (
                    "file_name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Original filename as uploaded by the user.",
                        max_length=255,
                    ),
                ),
                (
                    "file_size",
                    models.PositiveIntegerField(
                        blank=True, help_text="File size in bytes.", null=True
                    ),
                ),
                (
                    "mime_type",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="MIME type e.g. image/jpeg, application/pdf, video/mp4.",
                        max_length=127,
                    ),
                ),
                (
                    "s3_key",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="S3 object key. Never exposed to clients — use download_url instead.",
                        max_length=1024,
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        blank=True,
                        default="",
                        help_text="URL for Google Tasks links. Empty for local files.",
                    ),
                ),
                (
                    "link_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("email", "Email"),
                            ("generic", "Generic"),
                            ("chat_message", "Chat Message"),
                            ("keep_note", "Keep Note"),
                        ],
                        default="",
                        help_text="Google Tasks link type. Empty for local files.",
                        max_length=32,
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Optional description. Maps to Google Tasks link description.",
                        max_length=255,
                    ),
                ),
                (
                    "sync_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("synced", "Synced"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="pending",
                        help_text="Google attachments are created as synced. Local attachments start as pending.",
                        max_length=16,
                    ),
                ),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                ("deleted", models.BooleanField(db_index=True, default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="todos.task",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("owner_id", models.UUIDField(db_index=True)),
                ("name", models.CharField(max_length=64)),
                (
                    "color",
                    models.CharField(
                        default="#6B7280",
                        help_text="Hex color code e.g. #FF5733",
                        max_length=7,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("owner_id", "name"), name="unique_tag_per_user"
                    )
                ],
            },
        ),
        migrations.AddField(
            model_name="task",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                help_text="Local tags. Not synced to Google Tasks.",
                related_name="tasks",
                to="todos.tag",
            ),
        ),
        migrations.CreateModel(
            name="TaskList",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("owner_id", models.UUIDField(db_index=True)),
                ("title", models.CharField(max_length=255)),
                (
                    "color",
                    models.CharField(
                        default="#3B82F6",
                        help_text="Hex color code for UI display. Local only.",
                        max_length=7,
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        help_text="The default list is used when no list is specified for a new task.",
                    ),
                ),
                (
                    "external_id",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Google Tasks list ID. Empty until first sync.",
                        max_length=255,
                    ),
                ),
                (
                    "etag",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Google Tasks ETag for conflict detection.",
                        max_length=255,
                    ),
                ),
                (
                    "sync_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("synced", "Synced"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                ("deleted", models.BooleanField(db_index=True, default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-is_default", "title"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("deleted", False), ("is_default", True)),
                        fields=("owner_id",),
                        name="unique_default_list_per_user",
                    )
                ],
            },
        ),
        migrations.AddField(
            model_name="task",
            name="task_list",
            field=models.ForeignKey(
                blank=True,
                help_text="The list this task belongs to. Null means the user's default list.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tasks",
                to="todos.tasklist",
            ),
        ),
    ]
