# Generated by Django 6.0.4 on 2026-05-07 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todos", "0014_alter_task_options_remove_task_kind_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="due",
            field=models.DateTimeField(
                blank=True,
                help_text="Google Tasks only stores the date, not the time.",
                null=True,
            ),
        ),
    ]
