# Generated by Django 6.0.4 on 2026-07-27 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todos", "0015_alter_task_due"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attachment",
            name="sync_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("synced", "Synced"),
                    ("failed", "Failed"),
                    ("skipped", "Skipped"),
                ],
                db_index=True,
                default="pending",
                help_text="Google attachments are created as synced. Local attachments start as pending.",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="sync_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("synced", "Synced"),
                    ("failed", "Failed"),
                    ("skipped", "Skipped"),
                ],
                db_index=True,
                default="pending",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="tasklist",
            name="sync_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("synced", "Synced"),
                    ("failed", "Failed"),
                    ("skipped", "Skipped"),
                ],
                db_index=True,
                default="pending",
                max_length=16,
            ),
        ),
    ]
