# Generated by Django 6.0.4 on 2026-07-27 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todos", "0016_add_skipped_sync_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="GoogleSyncState",
            fields=[
                ("owner_id", models.UUIDField(primary_key=True, serialize=False)),
                (
                    "last_pulled_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Start time of the last successful pull. Null means never pulled.",
                        null=True,
                    ),
                ),
                ("last_attempted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "last_error",
                    models.CharField(blank=True, default="", max_length=512),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="task",
            constraint=models.UniqueConstraint(
                condition=models.Q(("external_id", ""), _negated=True),
                fields=("owner_id", "external_id"),
                name="unique_task_external_id_per_user",
            ),
        ),
        migrations.AddConstraint(
            model_name="tasklist",
            constraint=models.UniqueConstraint(
                condition=models.Q(("external_id", ""), _negated=True),
                fields=("owner_id", "external_id"),
                name="unique_list_external_id_per_user",
            ),
        ),
    ]
